ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_status VARCHAR(50) DEFAULT 'pending';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_id VARCHAR(255);

ALTER TABLE hub_members ADD COLUMN IF NOT EXISTS payment_id VARCHAR(255);
